name: Push to GCS

on:
  push:
    branches:
      - main

jobs:
  push_to_gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: '${{ secrets.GCP_SA_EMAIL }}'
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Synchronize public directory to GCS
        run: gsutil -m rsync -d -c -r frontend gs://resume.deepansh.app
